#! /bin/bash

Normal="$(tput sgr0)"
Reset="$(tput sgr0)"

Bold="$(tput bold)"
Dim="$(tput dim)"
ul="$(tput smul)"
xul="$(tput rmul)"
Reverse="$(tput rev)"

Black="$(tput setaf 0)"
Blue="$(tput setaf 4)"
Cyan="$(tput setaf 6)"
Green="$(tput setaf 2)"
Magenta="$(tput setaf 5)"
Red="$(tput setaf 1)"
White="$(tput setaf 7)"
Yellow="$(tput setaf 3)"

BlackBG="$(tput setab 0)"
BlueBG="$(tput setab 4)"
CyanBG="$(tput setab 6)"
GreenBG="$(tput setab 2)"
MagentaBG="$(tput setab 5)"
RedBG="$(tput setab 1)"
WhiteBG="$(tput setab 7)"
YellowBG="$(tput setab 3)"
