# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

export EDITOR=/usr/bin/vim
export SHELL=/bin/bash

source "${HOME}/.bashrc.d/.bash_prompt"

# erase duplicated entries, ignore entries that are duplicates or begin with spaces
export HISTCONTROL="erasedups:ignoreboth"
export HISTSIZE=50000
# unify history across bash sessions
export PROMPT_COMMAND="es=\$(exit_code); history -a; history -n"

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
# append to the history file instead of overwriting it
shopt -s histappend
# cd's to directories without having to type cd
shopt -s autocd
# correct spelling in cd targets
shopt -s cdspell
# attempts directory misspelling correction
shopt -s dirspell
# enables ** recursive glob expansion
shopt -s globstar

# bind -f .inputrc
#bind '"\e[A": history-search-backward'
#bind '"\e[B": history-search-forward'
bind -u delete-char
bind '"\C-d": kill-whole-line'
bind 'set show-all-if-ambiguous on'
#bind 'set completion-ignore-case on'

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# enable color support of ls
if [ "$TERM" != "dumb" ]; then
    eval "`dircolors -b`"
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

if [ -d ${HOME}/.bashrc.d ]; then
    for file in ${HOME}/.bashrc.d/*; do
        source "$file";
    done
fi

if [ -d ${HOME}/.bashrc.work ]; then
    for file in ${HOME}/.bashrc.work/*; do
        source "$file";
    done
fi
