# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# erase duplicated entries, ignore entries that are duplicates or begin with spaces
export HISTCONTROL="erasedups:ignoreboth"
export HISTSIZE=20000
# unify history across bash sessions
export PROMPT_COMMAND="history -a; history -r"

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
# append to the history file instead of overwriting it
shopt -s histappend
# cd's to directories without having to type cd
shopt -s autocd
# correct spelling in cd targets
shopt -s cdspell
# attempts directory misspelling correction
shopt -s dirspell
# enables ** recursive glob expansion
shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
#case "$TERM" in
#xterm-color)
#    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
#    ;;
#*)
#    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
#    ;;
#esac

# Comment in the above and uncomment this below for a color prompt
PS_ROOT="${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\][\[\033[01;34m\]\w\[\033[00m\]]"
PS1="${PS_ROOT}\$ "

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD/$HOME/~}\007"'
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
    #alias dir='ls --color=auto --format=vertical'
    #alias vdir='ls --color=auto --format=long'
fi

# work related aliases
if [ -f ~/.bash_aliases_work ]; then
    . ~/.bash_aliases_work
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

if [ -d ${HOME}/.bashrc.d ]; then
    for file in ${HOME}/.bashrc.d/*; do
        source "$file";
    done
fi

export EDITOR=/usr/bin/vim

#export GRAILS_HOME=/opt/grails
#PATH=$GRAILS_HOME/bin:$PATH
#
#export GRADLE_HOME=/opt/gradle
#PATH=$GRADLE_HOME/bin:$PATH
#
#export MAVEN_HOME=/opt/maven
#PATH=$MAVEN_HOME/bin:$PATH
#
#export JAVA_HOME=/opt/java
#PATH=$JAVA_HOME/bin:$PATH
#
#export SCALA_HOME=/opt/scala
#PATH=$SCALA_HOME/bin:$PATH
#
#PATH=~/bin:$PATH
#
#export PATH
